---
output: 
  pdf_document:
    citation_package: biblatex
    latex_engine: xelatex
  toc: false
  fig_caption: true
title: "Negro Leagues"
author: "Paul A. Hodgetts"
abstract: "As Bradshaw left, the lawyer looked at his watch. “And now, Poole, let us get to ours,” he said; and taking the poker under his arm, led the way into the yard. The scud had banked over the moon, and it was now quite dark. The wind, which only broke in puffs and draughts into that deep well of building, tossed the light of the candle to and fro about their steps, until they came into the shelter of the theatre, where they sat down silently to wait. London hummed solemnly all around; but nearer at hand, the stillness was only broken by the sounds of a footfall moving to and fro along the cabinet floor. Code available on GitHub: https://github.com/hodgettsp/nlmlb"
keywords: "Negro Leagues; Major League Baseball; baseball"
date: "`r format(Sys.time(), '%d %B %Y')`"
bibliography: references.bib
biblio-style: numeric
fontsize: 12pt
mainfont: Garamond
header-includes:
  - \usepackage{float} #use the 'float' package
  - \floatplacement{figure}{H} #make every figure with caption = h
geometry: margin = 1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, echo=F, message=F, warning=F}
# uncomment any packages that require installation

# install here package for accessing directories
# version 1.0.1
#install.packages("here")

# install tidyverse package for data stuff
# version 1.3.1
#install.packages("tidyverse")

#install.packages("kableExtra")
```

```{r libraries, echo=F, message=F, warning=F}
# load here package
# version 1.0.1
library(here)

# load tidyverse package
# version 1.3.1
library(tidyverse)

# load showtext package
# version 0.9-2
library(showtext)

library(kableExtra)
```

```{r source, echo=F, message=F, warning=F}
# load data files
source(here("script/rmarkdown/nl_mlb_count.R"))
source(here("script/prep/seamheads_prep.R"))
```



# Discussion



# Limitations

\newpage

# Appendix A: Tables

```{r seamheads-counts, echo=F, message=F, warning=F}
# pipe seamheads count data
seamheads_counts %>%
  # remove dummy row
  slice(-1) %>%
  # generate table using kableExtra package -> set caption, set booktabs to true, ->
  # set longtable to true
  kableExtra::kbl(caption = "Negro Leagues Player Counts, 1887-1948: Seamheads Data.", 
                  booktabs = T, 
                  longtable = T, 
                  col.names = c("Season", 
                                "Player Debut Count",
                                "Player Final Game Count",
                                "Player Count")) %>%
  # set table styling with position to center, ->
  # force the table position and repeat the header
  kableExtra::kable_styling(position = "center", 
                            latex_options = c("HOLD_position",
                                              "repeat_header"),
                            font_size = 10)
```

```{r wikipedia-counts, echo=F, message=F, warning=F}
# pipe wikipedia counts
wiki_counts %>%
  # remove dummy rows
  slice(-1, -84) %>%
  # generate table using kableExtra package
  kableExtra::kbl(caption = "Negro Leagues Player Counts, 1874-1975: Wikipedia Data.", 
                  booktabs = T, longtable = T, col.names = c("Season", "Player Debut Count",
                                                             " Player Final Game Count", "Player Count")) %>%
  # set kable styling for the table
  kableExtra::kable_styling(position = "center", 
                            latex_options = c("HOLD_position",
                                            "repeat_header"),
                            font_size = 10)
```

```{r askjdbfsakj, echo=F, message=F, warning=F}
nl_mlb_team_counts %>%
  filter(season >= 1947 & season <= 1950) %>%
  kableExtra::kbl(col.names = c("Season", "MLB Player Count", 
                                "NL Player MLB Count", 
                                "NL Players per MLB Team",
                                "NL Players per MLB Population",
                                "MLB Team", "No. of NL Players on Team"),
                  longtable = T,
                  booktabs = T,
                  caption = "Title") %>%
  kableExtra::kable_styling(position = "center", 
                            latex_options = c("HOLD_position",
                                            "repeat_header"),
                            font_size = 10) %>%
  kableExtra::column_spec(1, bold = T, width = ".35in") %>% 
  kableExtra::column_spec(2:5, width = ".5in") %>% 
  kableExtra::column_spec(7, width = ".5in")
```

# Appendix B: Charts

```{r seamheads-wiki-nl-count, echo=FALSE, message=F, warning=F, fig.align='center', fig.height=7.5, fig.width=13, fig.cap="The estimated distribution of players in the Negro Leagues, 1886 to 1948: Wikipedia-Seamheads comparison."}
source(here("script/rmarkdown/plots/wikipedia_seamheads_playercounts.R"))
seamheads_wiki_count
```
